// src/frontend/src/components/Counter/index.tsx
import * as React from "react";
import { connect } from "react-redux";
import { RouteComponentProps } from "react-router";
import { ApplicationState } from "../../store";
import * as CounterStore from "../../store/Counter";

type CounterProps = CounterStore.CounterState &
    typeof CounterStore.actionCreators &
    RouteComponentProps<{}>;

class Counter extends React.PureComponent<CounterProps> {
    public render() {
        return (
            <React.Fragment>
                <h1>Counter</h1>

                <p>This is a simple example of a React component.</p>

                <p aria-live="polite">
                    Current count: <strong>{this.props.count}</strong>
                </p>

                <button
                    type="button"
                    className="btn btn-primary btn-lg"
                    onClick={() => {
                        this.props.increment();
                    }}
                >
                    Increment
                </button>
            </React.Fragment>
        );
    }
}

export default connect(
    (state: ApplicationState) => state.counter,
    CounterStore.actionCreators
)(Counter);

// Sleet/ClientApp/src/app/counter/counter.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-counter-component',
  templateUrl: './counter.component.html'
})
export class CounterComponent {
  public currentCount = 0;

  public incrementCounter() {
    if (this.currentCount === 0) {
      this.currentCount++;
      return;
    }
    this.currentCount = this.currentCount + this.currentCount;
  }
}

<h1>Counter</h1>

<app-translation-component [CardName]="114514" [CardContent]="1919"></app-translation-component>

<p>This is a simple example of an Angular component.</p>


<p aria-live="polite">Current count: <strong>{{ currentCount }}</strong></p>

<button class="btn btn-primary" (click)="incrementCounter()">Increment</button>
